insert into marque (reference) values ('Mueller-Macejkovic');
insert into marque (reference) values ('Wolff-Fahey');
insert into marque (reference) values ('O''Reilly and Sons');
insert into marque (reference) values ('Gibson, Johns and Gutkowski');
insert into marque (reference) values ('Schmidt, McLaughlin and Macejkovic');
insert into marque (reference) values ('Harvey-Heathcote');
insert into marque (reference) values ('Marks LLC');
insert into marque (reference) values ('Nolan, Beahan and Schultz');
insert into marque (reference) values ('Jenkins-Roob');
insert into marque (reference) values ('Rempel, Rosenbaum and Boehm');
insert into marque (reference) values ('Rath, Pfeffer and Cole');
insert into marque (reference) values ('Haley, Jast and Leffler');
insert into marque (reference) values ('Bailey, Breitenberg and Spinka');
insert into marque (reference) values ('Reynolds LLC');
insert into marque (reference) values ('Graham, Murray and Hilpert');
insert into marque (reference) values ('Nikolaus LLC');
insert into marque (reference) values ('Pagac Inc');
insert into marque (reference) values ('Cormier LLC');
insert into marque (reference) values ('Emmerich-Shields');
insert into marque (reference) values ('Kuhlman-Connelly');
insert into marque (reference) values ('Huels-Kuphal');
insert into marque (reference) values ('Douglas-Miller');
insert into marque (reference) values ('Monahan, Tillman and Abshire');
insert into marque (reference) values ('Grant, Dibbert and Stehr');
insert into marque (reference) values ('Altenwerth, Wisozk and Lehner');
